# Generated by Django 6.0.5 on 2026-09-03 12:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_savedpaymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='receipt',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='receipt'),
        ),
    ]
