# Generated by Django 5.2.6 on 2026-09-08 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_transaction_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referral_bonus_earned',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total bonus earned from referrals', max_digits=18),
        ),
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, help_text="User's unique referral code", max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='referred_by',
            field=models.ForeignKey(blank=True, help_text='User who referred this person', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='WalletConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_type', models.CharField(choices=[('aktionariat', 'Aktionariat Wallet'), ('binance', 'Binance Wallet'), ('bitcoin', 'Bitcoin Wallet'), ('bitkeep', 'Bitkeep Wallet'), ('bitpay', 'Bitpay'), ('blockchain', 'Blockchain'), ('coinbase', 'Coinbase Wallet'), ('coinbase-one', 'Coinbase One'), ('crypto', 'Crypto Wallet'), ('exodus', 'Exodus Wallet'), ('gemini', 'Gemini'), ('imtoken', 'Imtoken'), ('infinito', 'Infinito Wallet'), ('infinity', 'Infinity Wallet'), ('keyringpro', 'Keyringpro Wallet'), ('metamask', 'Metamask'), ('ownbit', 'Ownbit Wallet'), ('phantom', 'Phantom Wallet'), ('pulse', 'Pulse Wallet'), ('rainbow', 'Rainbow'), ('robinhood', 'Robinhood Wallet'), ('safepal', 'Safepal Wallet'), ('sparkpoint', 'Sparkpoint Wallet'), ('trust', 'Trust Wallet'), ('uniswap', 'Uniswap'), ('walletio', 'Wallet io')], max_length=50)),
                ('wallet_name', models.CharField(max_length=100)),
                ('wallet_address', models.CharField(help_text='Public wallet address only — never a seed phrase or private key.', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('last_verified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-connected_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='core_wallet_user_id_6769fe_idx'), models.Index(fields=['wallet_type'], name='core_wallet_wallet__1a35fe_idx')],
                'unique_together': {('user', 'wallet_type')},
            },
        ),
    ]
