# Generated by Django 5.2.6 on 2026-09-08 14:04

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_user_referral_bonus_earned_user_referral_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='avg_loss_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='trader',
            name='avg_profit_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='trader',
            name='avg_score_7d',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='trader',
            name='avg_trade_time',
            field=models.CharField(blank=True, default='', help_text="e.g. '1 week', '3 weeks', '2 months'.", max_length=50),
        ),
        migrations.AddField(
            model_name='trader',
            name='badge',
            field=models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('bronze', 'Bronze')], default='bronze', max_length=10),
        ),
        migrations.AddField(
            model_name='trader',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='trader',
            name='country_flag',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='country flag'),
        ),
        migrations.AddField(
            model_name='trader',
            name='current_positions_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trader',
            name='expert_rating',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Rating out of 5.00.', max_digits=3),
        ),
        migrations.AddField(
            model_name='trader',
            name='profitable_weeks_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='trader',
            name='return_2y',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Return over 2 years, %.', max_digits=10),
        ),
        migrations.AddField(
            model_name='trader',
            name='return_ytd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Return Year To Date, %.', max_digits=10),
        ),
        migrations.AddField(
            model_name='trader',
            name='risk_score',
            field=models.PositiveSmallIntegerField(default=5, help_text='Risk score from 1 (conservative) to 10 (aggressive).'),
        ),
        migrations.AddField(
            model_name='trader',
            name='subscribers_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trader',
            name='total_losses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trader',
            name='total_trades_12m',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trader',
            name='total_wins',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trader',
            name='trades_count',
            field=models.PositiveIntegerField(default=0, help_text='Total number of trades this trader has taken.'),
        ),
        migrations.AddField(
            model_name='trader',
            name='trend_direction',
            field=models.CharField(choices=[('upward', 'Upward'), ('downward', 'Downward')], default='upward', max_length=10),
        ),
    ]
