# Generated by Django 5.2.6 on 2026-09-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_trader_avg_loss_pct_trader_avg_profit_pct_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trader',
            old_name='avg_loss_pct',
            new_name='avg_loss_percent',
        ),
        migrations.RenameField(
            model_name='trader',
            old_name='avg_profit_pct',
            new_name='avg_profit_percent',
        ),
        migrations.RenameField(
            model_name='trader',
            old_name='market_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='trader',
            old_name='copiers_count',
            new_name='copiers',
        ),
        migrations.RenameField(
            model_name='trader',
            old_name='cum_copiers',
            new_name='cumulative_copiers',
        ),
        migrations.RenameField(
            model_name='trader',
            old_name='cum_earnings',
            new_name='cumulative_earnings_copiers',
        ),
        migrations.RenameField(
            model_name='trader',
            old_name='current_positions_count',
            new_name='current_positions',
        ),
        migrations.RenameField(
            model_name='trader',
            old_name='followers_count',
            new_name='followers',
        ),
        migrations.RenameField(
            model_name='trader',
            old_name='roi',
            new_name='gain',
        ),
        migrations.RenameField(
            model_name='trader',
            old_name='min_capital',
            new_name='min_account_threshold',
        ),
        migrations.RenameField(
            model_name='trader',
            old_name='profitable_weeks_pct',
            new_name='profitable_weeks',
        ),
        migrations.RenameField(
            model_name='trader',
            old_name='risk_score',
            new_name='risk',
        ),
        migrations.RenameField(
            model_name='trader',
            old_name='subscribers_count',
            new_name='subscribers',
        ),
        migrations.RenameField(
            model_name='trader',
            old_name='trader_tags',
            new_name='tags',
        ),
        migrations.RenameField(
            model_name='trader',
            old_name='trades_count',
            new_name='trades',
        ),
        migrations.AddField(
            model_name='trader',
            name='capital',
            field=models.CharField(blank=True, default='', help_text="Capital under management, e.g. '50000'.", max_length=50),
        ),
        migrations.AddField(
            model_name='trader',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this trader available for copying?'),
        ),
        migrations.AddField(
            model_name='trader',
            name='username',
            field=models.CharField(blank=True, help_text="e.g. '@kristijan'.", max_length=100, null=True, unique=True),
        ),
    ]
