# Generated by Django 5.2.6 on 2026-09-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_rename_avg_loss_pct_trader_avg_loss_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trader',
            name='avg_trade_time',
            field=models.CharField(blank=True, choices=[('1 day', '1 Day'), ('3 days', '3 Days'), ('1 week', '1 Week'), ('2 weeks', '2 Weeks'), ('3 weeks', '3 Weeks'), ('1 month', '1 Month'), ('2 months', '2 Months'), ('3 months', '3 Months'), ('6 months', '6 Months')], default='', help_text="e.g. '1 week', '3 weeks', '2 months'.", max_length=50),
        ),
    ]
