# Generated by Django 5.2.6 on 2026-09-08 15:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_trader_avg_trade_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminwallet',
            name='qr_code',
            field=cloudinary.models.CloudinaryField(blank=True, help_text="Optional. Upload the wallet's official QR (e.g. from your exchange/wallet app) if it needs to encode more than just the raw address — such as a memo/destination tag some coins require. Leave blank to auto-generate a QR from the address instead.", max_length=255, null=True, verbose_name='qr_code'),
        ),
    ]
