# Generated by Django 5.2.6 on 2026-09-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_adminwallet_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioallocation',
            name='trader',
        ),
        migrations.RemoveField(
            model_name='tradehistory',
            name='trader',
        ),
        migrations.RemoveField(
            model_name='traderasset',
            name='trader',
        ),
        migrations.RemoveField(
            model_name='traderposition',
            name='trader',
        ),
        migrations.AlterUniqueTogether(
            name='tradersection',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tradersection',
            name='trader',
        ),
        migrations.RemoveField(
            model_name='trader',
            name='tags',
        ),
        migrations.AlterModelOptions(
            name='trader',
            options={'ordering': ['-gain', '-copiers']},
        ),
        migrations.RemoveField(
            model_name='trader',
            name='account_assets',
        ),
        migrations.RemoveField(
            model_name='trader',
            name='avatar_color',
        ),
        migrations.RemoveField(
            model_name='trader',
            name='master_pnl',
        ),
        migrations.RemoveField(
            model_name='trader',
            name='profit_share',
        ),
        migrations.RemoveField(
            model_name='trader',
            name='risk_level',
        ),
        migrations.RemoveField(
            model_name='trader',
            name='specialty',
        ),
        migrations.RemoveField(
            model_name='trader',
            name='win_rate',
        ),
        migrations.AddField(
            model_name='trader',
            name='frequently_traded',
            field=models.JSONField(blank=True, default=list, help_text='List of frequently traded asset tickers.'),
        ),
        migrations.AddField(
            model_name='trader',
            name='monthly_performance',
            field=models.JSONField(blank=True, default=list, help_text='Monthly performance percentages as list of {month, percentage}.'),
        ),
        migrations.AddField(
            model_name='trader',
            name='performance_data',
            field=models.JSONField(blank=True, default=list, help_text='Monthly performance data as list of {month, value}.'),
        ),
        migrations.AddField(
            model_name='trader',
            name='portfolio_breakdown',
            field=models.JSONField(blank=True, default=list, help_text='e.g. [{"name": "ETF", "percentage": 25}, {"name": "Crypto", "percentage": 75}]'),
        ),
        migrations.AddField(
            model_name='trader',
            name='top_traded',
            field=models.JSONField(blank=True, default=list, help_text='e.g. [{"name": "Apple Inc", "ticker": "AAPL", "avg_profit": 12.5, "avg_loss": -3.2, "profitable_pct": 78}]'),
        ),
        migrations.AlterField(
            model_name='trader',
            name='avg_trade_time',
            field=models.CharField(blank=True, choices=[('1 day', '1 Day'), ('3 days', '3 Days'), ('1 week', '1 Week'), ('2 weeks', '2 Weeks'), ('3 weeks', '3 Weeks'), ('1 month', '1 Month'), ('2 months', '2 Months'), ('3 months', '3 Months'), ('6 months', '6 Months')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='trader',
            name='cumulative_earnings_copiers',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='trader',
            name='gain',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Overall gain, %.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='trader',
            name='max_drawdown',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='trader',
            name='min_account_threshold',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.DeleteModel(
            name='DummyCopier',
        ),
        migrations.DeleteModel(
            name='PortfolioAllocation',
        ),
        migrations.DeleteModel(
            name='TradeHistory',
        ),
        migrations.DeleteModel(
            name='TraderAsset',
        ),
        migrations.DeleteModel(
            name='TraderPosition',
        ),
        migrations.DeleteModel(
            name='TraderSection',
        ),
        migrations.DeleteModel(
            name='TraderTag',
        ),
        migrations.AddField(
            model_name='trader',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Badge tags, e.g. ["Trending Investors", "Rising Stars"]'),
        ),
    ]
