# Generated by Django 5.2.6 on 2026-09-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_remove_portfolioallocation_trader_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='portfolio_target',
            field=models.DecimalField(blank=True, decimal_places=2, default=50000, help_text="Admin-set portfolio target shown as a progress bar on the user's dashboard.", max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='portfolio_target_visible',
            field=models.BooleanField(default=False, help_text="Show the Portfolio Target progress bar on the user's dashboard."),
        ),
    ]
