# Generated by Django 5.2.6 on 2026-09-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_user_portfolio_target_user_portfolio_target_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_loyalty_status',
            field=models.CharField(choices=[('iron', 'Iron'), ('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('diamond', 'Diamond'), ('elite', 'Elite')], default='iron', help_text='Current loyalty tier.', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='next_amount_to_upgrade',
            field=models.DecimalField(decimal_places=2, default=5000, help_text='Total completed deposits required to reach the next loyalty tier.', max_digits=20),
        ),
        migrations.AddField(
            model_name='user',
            name='next_loyalty_status',
            field=models.CharField(choices=[('iron', 'Iron'), ('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('diamond', 'Diamond'), ('elite', 'Elite')], default='bronze', help_text='Next loyalty tier.', max_length=20),
        ),
    ]
