# Generated by Django 6.0.5 on 2026-09-10 18:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_user_current_loyalty_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminwallet',
            name='icon',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Legacy manual override — no longer needed. The icon is now picked automatically from the selected currency.', max_length=255, null=True, verbose_name='icon'),
        ),
    ]
