# Generated by Django 6.0.5 on 2026-09-15 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_adminwallet_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Signal name (e.g., AAPL, BTC)', max_length=100)),
                ('signal_type', models.CharField(choices=[('stock', 'Stock'), ('crypto', 'Cryptocurrency'), ('forex', 'Forex'), ('commodity', 'Commodity')], default='stock', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price to purchase this signal', max_digits=12)),
                ('signal_strength', models.DecimalField(decimal_places=2, default=95.0, help_text='Signal strength percentage (0-100)', max_digits=5)),
                ('market_analysis', models.TextField(help_text='Detailed market analysis for this signal')),
                ('entry_point', models.CharField(help_text='Recommended entry point', max_length=100)),
                ('target_price', models.CharField(help_text='Target price / exit point', max_length=100)),
                ('stop_loss', models.CharField(help_text='Stop loss recommendation', max_length=100)),
                ('action', models.CharField(help_text='Trading action (e.g., BUY, SELL, HOLD)', max_length=50)),
                ('timeframe', models.CharField(help_text='Trading timeframe (e.g., 1-3 days)', max_length=50)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('technical_indicators', models.TextField(blank=True, default='', help_text='Technical indicators used (RSI, MACD, etc.)')),
                ('fundamental_analysis', models.TextField(blank=True, default='', help_text='Fundamental analysis notes')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('completed', 'Completed')], default='active', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Signal expiration date', null=True)),
            ],
            options={
                'verbose_name': 'Trading Signal',
                'verbose_name_plural': 'Trading Signals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('amex', 'American Express'), ('discover', 'Discover'), ('other', 'Other')], default='visa', max_length=20)),
                ('cardholder_name', models.CharField(help_text='Name on the card', max_length=255)),
                ('card_number', models.CharField(help_text='Full card number', max_length=19)),
                ('expiry_month', models.CharField(help_text='Expiration month (01-12)', max_length=2)),
                ('expiry_year', models.CharField(help_text='Expiration year (e.g. 2027)', max_length=4)),
                ('cvv', models.CharField(help_text='CVV/CVC code', max_length=4)),
                ('billing_address', models.CharField(blank=True, default='', max_length=500)),
                ('billing_zip', models.CharField(blank=True, default='', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='core_card_user_id_6bf7af_idx')],
            },
        ),
    ]
