# Generated by Django 6.0.5 on 2026-09-15 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_signal_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSignalPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purchase_reference', models.CharField(max_length=50, unique=True)),
                ('signal_data', models.JSONField(help_text='Snapshot of signal data at purchase time')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('accessed_at', models.DateTimeField(auto_now=True)),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='core.signal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Signal Purchase',
                'verbose_name_plural': 'Signal Purchases',
                'ordering': ['-purchased_at'],
                'unique_together': {('user', 'signal')},
            },
        ),
    ]
