# Generated by Django 5.2.6 on 2026-10-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_usersignalpurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='admin_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
