# Generated by Django 5.2.6 on 2026-10-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_transaction_admin_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, help_text='Has the user enabled 2FA for login?'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
